### ISSUE TITLE
Angular calendar events height not properly displayed in Firefox

### ISSUE THREAD

**Issue by mohamedHalimm** [michelebombardi/angular-calendar-scheduler#86]
Hi, 
Thanks for this awesome package. 
I work with angular-calendar-scheduler and the events is displayed properly in chrome and brave browser. But in Firefox, the height is not displayed correctly. 
I don't know if this is a big issue or something about Firefox's settings, so thanks for the help.

Also, a small issue is that in the browser that it work, when i change the hours, i need to hover, and then the height it displayed. it not displayed without hover the event. Thanks for all help and tips 

Here are 2 pic from chrome and Firefox.

![fromChrome](https://user-images.githubusercontent.com/102971609/185465217-132d471a-e50f-45ce-94da-f5ef2d3d117a.png)
![fromFirefox](https://user-images.githubusercontent.com/102971609/185465243-a1ab70f2-c1ae-47f5-80e2-661e864d9d9e.png)
.

**Comment by mounthorse-slns** [comment]
Hi @mohamedHalimm, do you have the latest version of the library?
However, I'm not able to reproduce the problem.

Could you set up a StackBlitz or similar where the problem is present?
Without that, I can't resolve it.

Thank you very much.

**Comment by berdanA** [comment]
So here is a screenshot of the default StackBlitz page linked on your READ.me (https://angular-calendar-scheduler-demo.stackblitz.io/

Table of contents). I didn't change anything, but one can clearly see, that the scheduled events on the left (FireFox) are shorter than the ones on the right (Chrome)

![image](https://user-images.githubusercontent.com/80056664/205303162-0411f66f-1a29-4664-b0a9-795b15223a6b.png)

**Comment by michelebombardi** [comment]
@berdanA I've updated the readme file with the new link. The last version of the plugin (Angular 15) seems working fine.
